--[[
    ~ pm. A package manager by Hugo Coto.
]] --

-- Add ~/.config/pm/ to the path
package.path = package.path .. ";" .. os.getenv("HOME") .. "/.config/pm/?.lua"

-- System configuration
System = {
    build = { path = os.getenv("HOME") .. "/.local/share/pm/cache/" }, -- Build path
    bin = { path = os.getenv("HOME") .. "/.local/share/pm/bin/" },     -- Bin path
}

local ur = require 'ur'

--[[
    Package possible fields:
    - url: url to the file
    - name: name of the file downloaded from url
    - build: build script that generates the artifact
    - artifact: name of the executable generated by the build script
    - last_modified_cmd: custom command to get Last-Modified date
]] --
Packages = {
    {
        -- pm bootstraping. Keep pm updated.
        url = "https://github.com/hugoocoto/pm/releases/download/nightly/pm-x86_64.AppImage",
        build = "chmod +x pm",
        name = "pm",
    },

    ur.Fetch { user = "hugoocoto", file = "nvim-nightly/nvim.lua" },
    ur.Fetch { user = "hugoocoto", file = "helium/helium.lua" },

    -- My tools
    ur.Fetch { user = "hugoocoto", file = "wallpaper/wallpaper.lua" },
    ur.Fetch { user = "hugoocoto", file = "dv/dv.lua" },
    ur.Fetch { user = "hugoocoto", file = "todo/todo.lua" },
    ur.Fetch { user = "hugoocoto", file = "vicel/vicel.lua" },
    ur.Fetch { user = "hugoocoto", file = "fetch/fetch.lua" },
    ur.Fetch { user = "hugoocoto", file = "eqnx/eqnx.lua" },
    ur.Fetch { user = "hugoocoto", file = "yaci/yaci.lua" },
    ur.Fetch { user = "hugoocoto", file = "zrun/zrun.lua" },
    ur.Fetch { user = "hugoocoto", file = "pdfjoin/pdfjoin.lua" },
    ur.Fetch { user = "hugoocoto", file = "b/b.lua" },
    ur.Fetch { user = "hugoocoto", file = "tetris/tetris.lua" },
    ur.Fetch { user = "hugoocoto", file = "st/st.lua" },
}
