--[[
    ~ pm. A package manager by Hugo Coto.
]] --

-- Add ~/.config/pm/ to the path
package.path = package.path .. ";" .. os.getenv("HOME") .. "/.config/pm/?.lua"

-- System configuration
System = {
    build = { path = os.getenv("HOME") .. "/.local/share/pm/cache/" }, -- Build path
    bin = { path = os.getenv("HOME") .. "/.local/share/pm/bin/" },     -- Bin path
}

require('github')

--[[
    Package possible fields:
    - url: url to the file
    - name: name of the file downloaded from url
    - build: build script that generates the artifact
    - artifact: name of the executable generated by the build script
    - last_modified_cmd: custom command to get Last-Modified date
]] --
Packages = {
    {
        -- pm bootstraping. Keep pm updated.
        url = "https://github.com/hugoocoto/pm/releases/download/nightly/pm-x86_64.AppImage",
        build = "chmod +x pm",
        name = "pm",
    },

    require 'nvim',
    require 'helium',

    Github { user = "hugoocoto", repo = "dv" },
    Github { user = "hugoocoto", repo = "todo" },
    Github { user = "hugoocoto", repo = "vicel", cmd = "make release" },
    Github { user = "hugoocoto", repo = "fetch" },
    Github { user = "hugoocoto", repo = "eqnx" },
    Github { user = "hugoocoto", repo = "yaci" },
    Github { user = "hugoocoto", repo = "zrun", cmd="zig build", artifact="zig-out/bin/zrun" },
    Github { user = "hugoocoto", repo = "pdfjoin", cmd = "chmod +x pdfjoin" },
    Github { user = "hugoocoto", repo = "b" , cmd="make b && make desktop-entry"},
    Github { user = "hugoocoto", repo = "tetris" },
}
