--[[
    ~ pm. A package manager by Hugo Coto.
]] --

-- Add ~/.config/pm/ to the path
package.path = package.path .. ";" .. os.getenv("HOME") .. "/.config/pm/?.lua"

-- System configuration
System = {
    build = { path = os.getenv("HOME") .. "/.local/share/pm/cache/" }, -- Build path
    bin = { path = os.getenv("HOME") .. "/.local/share/pm/bin/" },     -- Bin path
}

require('github')

--[[
    Package possible fields:
    - url: url to the file
    - name: name of the file downloaded from url
    - build: build script that generates the artifact
    - artifact: name of the executable generated by the build script
    - last_modified_cmd: custom command to get Last-Modified date
]] --
Packages = {
    {
        -- pm bootstraping. Keep pm updated.
        url = "https://github.com/hugoocoto/pm/releases/download/nightly/pm.tar.gz",
        build = "tar -xzf pm.tar.gz && make",
        artifact = "pm",
    },
    require 'nvim',

    Github_make("hugoocoto", "dv", "main", "dv"),
    Github_make("hugoocoto", "todo", "main", "todo"),
    Github_make("hugoocoto", "vicel", "main", "vicel"),
    Github_make("hugoocoto", "fetch", "main", "fetch"),
}
