#define _GNU_SOURCE

#include <assert.h>
#include <curl/curl.h>
#include <curl/easy.h>
#include <dirent.h>
#include <err.h>
#include <errno.h>
#include <fcntl.h>
#include <libgen.h>
#include <openssl/evp.h>
#include <pthread.h>
#include <sched.h>
#include <semaphore.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/file.h>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
#include <utime.h>

#define INCLUDE_CONF_IMPLEMENTATION
#include "conf.h"

#define FS_IMPLEMENTATION
#include "fs.h"

#include "cum.h"
#include "flag.h"

// The fields that can be used in each package
// (name, required?, description)
#define FIELD_LIST                                                                    \
        FIELD(url, true, "url to the file")                                           \
        FIELD(name, false, "name of the file downloaded from url")                    \
        FIELD(build, true, "build script that generates the artifact")                \
        FIELD(artifact, true, "name of the executable generated by the build script") \
        FIELD(last_modified_cmd, false, "custom command to get Last-Modified date")

typedef struct Task {
        const char *build_path;
        const char *bin_path;
#define FIELD(x, ...) const char *x;
        FIELD_LIST
#undef FIELD
        pthread_t thr;
} Task;

int threads_number = 0;
sem_t *sem = NULL;

int
nproc()
{
        cpu_set_t set;
        if (sched_getaffinity(0, sizeof(set), &set) == 0) {
                int n = CPU_COUNT(&set);
                if (n > 0) return n;
        }
        long n = sysconf(_SC_NPROCESSORS_ONLN);
        return n > 0 ? (int) n : 1;
}

char *
format(const char *fmt, ...)
{
        va_list ap;
        char *buf;
        va_start(ap, fmt);
        vasprintf(&buf, fmt, ap);
        va_end(ap);
        assert(buf);
        return buf;
}

size_t
_download_write(char *ptr, size_t size, size_t nmemb, void *stream)
{
        size_t n = fwrite(ptr, size, nmemb, (FILE *) stream);
        return n * size;
}

int
download(const char *url, const char *path)
{
        CURLcode result = !CURLE_OK;
        CURL *curl = NULL;
        FILE *f = NULL;

        if ((f = fopen(path, "wb")) == NULL) {
                perror(path);
                goto err;
        }

        if ((curl = curl_easy_init()) == NULL) goto err;

        curl_easy_setopt(curl, CURLOPT_URL, url);
        curl_easy_setopt(curl, CURLOPT_FOLLOWLOCATION, 1L);             /* follow redirects */
        curl_easy_setopt(curl, CURLOPT_NOPROGRESS, 1L);                 /* disable progress var if 1 */
        curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, _download_write); /* send all data to the write callback */
        curl_easy_setopt(curl, CURLOPT_WRITEDATA, f);

        if ((result = curl_easy_perform(curl)) != CURLE_OK) goto err;

        long http_code = 0;
        curl_easy_getinfo(curl, CURLINFO_RESPONSE_CODE, &http_code);
        if (http_code >= 400) {
                fprintf(stderr, "Download failed: HTTP %ld from %s\n", http_code, url);
                result = CURLE_HTTP_RETURNED_ERROR;
                goto err;
        }

err:
        if (curl) curl_easy_cleanup(curl);
        if (f) fclose(f);
        return !(result == CURLE_OK);
}

int
cmd_run(const char *cmd, const char *root_path)
{
        int status;
        int pid = fork();
        switch (pid) {
        case -1:
                perror("fork");
                return -1;
        case 0:
                if (chdir(root_path)) err(EXIT_FAILURE, "cd %s", root_path);
                execlp("sh", "sh", "-c", cmd, NULL);
                err(EXIT_FAILURE, "sh -c %s", cmd);
        default:
                if (waitpid(pid, &status, 0) == -1) {
                        perror("waitpid");
                        return -1;
                }
                return status;
        }
}

char *
cmd_run_and_get(const char *cmd)
{
        char t[4096] = "";
        int status = 0;
        FILE *const p = popen(cmd, "r");

        if (p) fgets(t, sizeof t - 1, p);
        if (p) status |= pclose(p);
        return status == 0 && t[0] ? strdup(t) : NULL;
}

int
dir_lock_acquire(const char *dir)
{
        int fd = open(dir, O_RDONLY | O_DIRECTORY);
        if (fd < 0) {
                perror("dir_lock_acquire open");
                return -1;
        }
        if (flock(fd, LOCK_EX)) {
                perror("dir_lock_acquire flock");
                close(fd);
                return -1;
        }
        return fd;
}

int
dir_lock_release(int fd)
{
        if (fd < 0) return 0;
        if (flock(fd, LOCK_UN)) {
                perror("dir_lock_release flock");
                close(fd);
                return 1;
        }
        close(fd);
        return 0;
}

time_t
url_file_get_modification_time(const char *url, const char *custom_cmd, int custom_cmd_prefix_len)
{
        struct tm tm = { 0 };
        char weekday[4], month_str[4];
        assert(url);
        char *buf = NULL;
        int offset;
        char *cmd;

        if (custom_cmd) {
                buf = cmd_run_and_get(custom_cmd);
                offset = custom_cmd_prefix_len;
        }
        if (!buf) {
                buf = cmd_run_and_get(cmd = format("curl -sIL %s | grep -i last-modified", url));
                offset = strlen("last-modified: ");
                free(cmd);
        }
        if (!buf) goto err;

        if (sscanf(buf + offset, "%3s, %d %3s %d %d:%d:%d GMT",
                   weekday, &tm.tm_mday, month_str, &tm.tm_year,
                   &tm.tm_hour, &tm.tm_min, &tm.tm_sec) != 7) {
                goto err;
        }
        tm.tm_year -= 1900;

        const char *months[] = { "Jan", "Feb", "Mar", "Apr", "May", "Jun",
                                 "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" };

        tm.tm_mon = -1;
        for (int i = 0; i < 12; i++) {
                if (strncmp(month_str, months[i], 3) == 0) {
                        tm.tm_mon = i;
                        break;
                }
        }
        if (tm.tm_mon == -1) goto err;

        if (buf) free(buf);
        return timegm(&tm);
err:
        if (buf) free(buf);
        errno = EINVAL;
        return -1;
}

char *
url_get_filename(const char *url)
{
        const char *c = strrchr(url, '/');
        if (c == NULL) return NULL; // no '/' in the url
        if (c[1] == 0) return NULL; // url ends with '/' -> no filename
        return strdup(c + 1);
}

int
build_package(const char *build, const char *artifact, const char *bpath, const char *artifact_src, const char *xname, const char *bname)
{
        printf("[%s] Building...\n", artifact);

        printf("[%s] > sh -c '%s'\n", artifact, build);
        if (cmd_run(build, bpath)) {
                fprintf(stderr, "[%s] Error: cmd_run %s: %s\n", artifact, build, strerror(errno));
                fprintf(stderr, "[%s] Removing corrupted cached file: %s\n", artifact, bname);
                remove(bname);
                return 1;
        }
        printf("[%s] > cp %s %s\n", artifact, artifact_src, xname);
        if (copy(artifact_src, xname)) {
                fprintf(stderr, "[%s] Error: copy %s %s: %s\n", artifact, artifact_src, xname, strerror(errno));
                return 1;
        }

        printf("[%s] Package built succesfully\n", artifact);

        return 0;
}

int
#define FIELD(x, ...) const char *x,
process_package(FIELD_LIST const char *bdir, const char *xdir)
#undef FIELD
{
        /* REQUIRED ARGS HAVE TO BE SET */
        int status = 0;
        char *fname = NULL; // downloaded file name
        char *bpath = NULL; // build path
        char *bname = NULL; // build name: bpath / fname
        char *xpath = NULL; // bin path
        char *xname = NULL; // bin name: xpath / artifact
        char *artifact_src = NULL;
        int bfd = -1;

        if ((fname = name ? strdup(name) : url_get_filename(url)) == NULL) goto err;
        if ((bpath = format("%s/%s", bdir, fname)) == NULL) goto err;
        if ((bname = format("%s/%s", bpath, fname)) == NULL) goto err;
        if ((xpath = format("%s", xdir)) == NULL) goto err;
        if ((xname = format("%s/%s", xpath, artifact)) == NULL) goto err;
        if ((artifact_src = format("%s/%s", bpath, artifact)) == NULL) goto err;

        if (mkdirp(bpath, 0755)) goto err;
        if (mkdirp(xpath, 0755)) goto err;

        if ((bfd = dir_lock_acquire(bpath)) < 0) goto err;

        if (!file_exists(bname)) {
                printf("[%s] File not found. Downloading...\n", artifact);
                if (download(url, bname)) goto err;
                printf("[%s] File downloaded successfully\n", artifact);
                goto build;
        }

        // harcoded prefix len for custom command because I dont support parsing ints
        time_t t0 = url_file_get_modification_time(url, last_modified_cmd, strlen("last-modified: "));
        time_t t1 = file_get_modification_date(bname);

        if (t0 < 0) {
                printf("[%s] Can not fetch url date from %s: %s\n", artifact, url, strerror(errno));
                goto err;
        }

        if (t1 < 0 || t0 > t1) {
                printf("[%s] File is newer. Downloading...\n", artifact);
                if (download(url, bname)) goto err;
                goto build;
        } else {
                printf("[%s] File is updated.\n", artifact);
                if (!file_exists(xname)) {
                        goto build;
                }
                goto exit;
        }

build:
        if (build_package(build, artifact, bpath, artifact_src, xname, bname)) goto err;
        goto exit;
err:
        status = 1;
        printf("[%s] Error: Package not installed\n", artifact);
exit:
        if (bfd >= 0) dir_lock_release(bfd);
        if (fname) free(fname);
        if (bpath) free(bpath);
        if (bname) free(bname);
        if (xpath) free(xpath);
        if (xname) free(xname);
        if (artifact_src) free(artifact_src);
        return status;
}

void
dump_config(const char *file)
{
        FILE *f = fopen(file, "w");
#define $(x, ...) fprintf(f, x "\n", ##__VA_ARGS__)
        $("--[[");
        $("    ~ pm. A package manager by Hugo Coto.");
        $("]] --");
        $("");
        $("-- Add ~/.config/pm/ to the path");
        $("package.path = package.path .. \";\" .. os.getenv(\"HOME\") .. \"/.config/pm/?.lua\"");
        $("");
        $("-- Build path");
        $("Build = {");
        $("    path = os.getenv(\"HOME\") .. \"/.local/share/pm/cache/\"");
        $("}");
        $("");
        $("-- Bin path");
        $("Bin = {");
        $("    path = os.getenv(\"HOME\") .. \"/.local/share/pm/bin/\"");
        $("}");
        $("");
        $("--[[");
        $("    Package possible fields:");
#define FIELD(x, _, desc) $("    - " #x ": " desc);
        FIELD_LIST;
#undef FIELD
        $("]] --");
        $("Packages = {");
        $("    {");
        $("        -- pm bootstraping. Keep pm updated.");
        $("        url = \"https://github.com/hugoocoto/pm/releases/download/nightly/pm.tar.gz\",");
        $("        build = \"tar -xzf pm.tar.gz && make\",");
        $("        artifact = \"pm\",");
        $("    },");
        $("}");
#undef $
        fclose(f);
}

void *
process_package_wrapper(void *arg)
{
        Task *t = (Task *) arg;

#define FIELD(x, ...) t->x,
        process_package(FIELD_LIST t->build_path, t->bin_path);
#undef FIELD
        sem_post(sem); // release lock

#define FIELD(x, ...)                \
        if (t->x) {                  \
                free((void *) t->x); \
        }
        FIELD_LIST;
#undef FIELD
        return 0;
}

int
load_config(const char *config_path, int dump_and_exit, int list_and_exit)
{
        const char *build_path = NULL; // build path (Lua Build.path)
        const char *bin_path = NULL;   // bin path (Lua Bin.path)
        Conf conf;
        int len;

        if (Conf_open(&conf, config_path)) {
                err(EXIT_FAILURE, "Can not open file %s", config_path);
        }

        if (Conf_get_str(conf, &build_path, "Build.path")) {
                errx(EXIT_FAILURE, "Error: field `Build = { path = \"\" }` is required. (In %s)", config_path);
        }

        if (Conf_get_str(conf, &bin_path, "Bin.path")) {
                errx(EXIT_FAILURE, "Error: field `Bin = { path = \"\" }` is required. (In %s)", config_path);
        }

        if (mkdirp(build_path, 0755)) err(EXIT_FAILURE, "mkdir %s", build_path);
        if (mkdirp(bin_path, 0755)) err(EXIT_FAILURE, "mkdir %s", bin_path);

        if (Conf_get_len(conf, &len, "Packages")) return 1;

        if (dump_and_exit) {
                printf("Config\n");
                printf("  Config path: %s\n", config_path);
                printf("  Build  path: %s\n", build_path);
                printf("  Binary path: %s\n", bin_path);
                printf("  Packages: %d\n", len);
                printf("  Threads: %d\n", threads_number);
                goto exit;
        }

        Da(Task) tasks = { 0 };

        Task t;
        for (int i = 1; i <= len; i++) {
                t.build_path = build_path;
                t.bin_path = bin_path;

/*           */ #define FIELD(x, ...) t.x = NULL;
                FIELD_LIST;
/*           */ #undef FIELD

/*           */ #define FIELD(x, ...)                                          \
        /*   */ if (Conf_get_str(conf, &t.x, "Packages.%d." #x, i) == CONF_OK) \
                /*   */ t.x = strdup(t.x);
                FIELD_LIST;
/*           */ #undef FIELD

/*           */ #define FIELD(x, ...) t.x == NULL &&
                if (FIELD_LIST 1) {
                        printf("  Empty. Skipping...\n");
                        continue;
                } // all the fields are null - empty package
/*           */ #undef FIELD

                // allow ignoring artifact for direct downloaded files
                if (!t.artifact && t.name) t.artifact = strdup(t.name);

/*           */ #define FIELD(x, req, ...) \
        /*   */ if (t.x == NULL && req)    \
                /*   */ printf("  Error: required field '" #x "' not set\n");
                FIELD_LIST
/*           */ #undef FIELD

/*           */ #define FIELD(x, req, ...) (t.x || !req) &&
                if (!(FIELD_LIST 1)) return 1;
/*           */ #undef FIELD

                t.thr = 0;
                Da_append(&tasks, t);
        }

        if (list_and_exit) {
                printf("Packages:\n");
                Da_foreach(t, tasks)
                {
                        printf("  %s  (%s)\n", t->artifact, t->url);
                }
                return 0;
        }

        Da_foreach(t, tasks)
        {
                sem_wait(sem);
                if (pthread_create(&t->thr, NULL, process_package_wrapper, t)) {
                        perror("pthread_create");
                        sem_post(sem);
                        goto err;
                }
        }

        Da_foreach(t, tasks)
        {
                if (pthread_join(t->thr, NULL)) {
                        perror("pthread_join");
                }
        }

        Da_destroy(&tasks);

err:
exit:
        if (Conf_close(conf)) return 1;
        return 0;
}

int
main(int argc, char **argv)
{
        const char *init_config;
        const char *dump_and_exit;
        const char *list_and_exit;
        const char *nthreads;
        const char *home;
        const char *version;
        char *file;

        flag_program(.help = NULL); // unused. Just to suppress the unused warning
        flag_add(&version, "--version", "-v", .help = "Show version");
        flag_add(&init_config, "i", "init", .help = "Create init.lua");
        flag_add(&nthreads, "t", "threads", .help = "Use T threads", .nargs = 1);
        flag_add(&dump_and_exit, "s", "system", .help = "Show system configuration");
        flag_add(&list_and_exit, "l", "list", .help = "List packages in config");

        if (flag_parse(&argc, &argv) || argc > 1) {
                flag_show_help(STDOUT_FILENO);
                exit(1);
        }

        if (version) {
                printf("pm version v0.1 (%s %s)\n", __DATE__, __TIME__);
                printf("Copyright (C) 2026 Hugo Coto\n");
                printf("This is free software: you are free to change and redistribute it.\n");
                printf("There is NO WARRANTY, to the extent permitted by law.\n");
                return 0;
        }

        curl_global_init(CURL_GLOBAL_ALL);

        threads_number = nthreads ? atoi(nthreads) : nproc();
        if (threads_number <= 0) {
                errx(EXIT_FAILURE, "Threads number can not be 0 or less");
        }

        sem = (sem_t *) malloc(sizeof(sem_t));
        if (sem_init(sem, 0, threads_number)) {
                errx(EXIT_FAILURE, "sem_init");
        }

        if (!(home = getenv("HOME"))) {
                errx(EXIT_FAILURE, "Error: $HOME is not set\n");
        }

        file = format("%s/.config/pm/init.lua", home);
        assert(file);

        if (init_config) {
                char *cpyfile = strdup(file);
                assert(cpyfile);
                char *bn = dirname(cpyfile);
                mkdirp(bn, 0755);
                free(cpyfile);
                dump_config(file);
                printf("New config file: %s\n", file);
        }

        if (load_config(file, dump_and_exit != 0, list_and_exit != 0)) {
                printf("Error loading config file %s\n", file);
        }
        free(file);
        flag_free();
        curl_global_cleanup();
        sem_destroy(sem);
        return 0;
}
